name: Build

on:
  push: 
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Build
        run: npm run build

