name: Renovate

on:
  schedule:
    - cron: "0 3 * * *" # Run at 3 AM every Monday
  workflow_dispatch: # Allow manual trigger

permissions:
  pull-requests: write
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run renovate
        uses: renovatebot/github-action@v46.1.14
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
