name: Renovate

on:
  schedule:
    - cron: "0 3 * * 1" # Run at 3 AM every Monday
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.14
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
